name: Publish

on:
  push:
    branches:
      - stable

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MiniConda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
        channels: readdy,conda-forge
    - name: Install Conda Deps
      shell: bash -l {0}
      run: |
        conda install readdy
    - name: Install Project Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install .[all]
    - name: Install Build Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build Package
      shell: bash -l {0}
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@main
      with:
        user: aicspypi
        password: ${{ secrets.PYPI_TOKEN }}
