name: Test and Lint

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup MiniConda
      uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: readdy/label/dev,conda-forge
    - name: Install Conda Deps
      run: |
        conda install readdy
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest --cov-report xml --cov=simulariumio simulariumio/tests/
    - name: Upload codecov
      uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup MiniConda
      uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.8
          channels: readdy/label/dev,conda-forge
    - name: Install Conda Deps
      run: |
        conda install readdy
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 simulariumio --count --verbose --show-source --statistics
        black --check --exclude vendor simulariumio
